### PR TITLE
update scalafix 0.9.11 - sbt 1.3.8 - sbt-ci-release 1.5.2

### PR DESCRIPTION
**Pull request by enzief**

### CODE REVIEW

**Comment by enzief** [comment]
Hello @vovapolu would you please have a look?

**Comment by vovapolu** [comment]
Thank you! :+1:

**Comment by enzief** [comment]
Would you mind bumping the version too?

**Comment by vovapolu** [comment]
@enzief I have invited you to the repo. It should allow you to merge PRs and draft releases without my long responses :D

**Comment by enzief** [comment]
Thank you! I'm happy if I can help with anything.

**Pull request merged**
