### PR TITLE
Update to scalafix 0.9.4

### PR DESCRIPTION
**Pull request by enzief**
... and sbt 1.2.8

### CODE REVIEW

**Comment by enzief** [comment]
@vovapolu could you have a look please?

**Comment by vovapolu** [comment]
Sorry, missed notification about new PR. 
Looks good :+1:

**Comment by enzief** [comment]
Can we have a minor release for this? I want to introduce it at work.

**Comment by vovapolu** [comment]
@enzief Yeah, sure

**Comment by vovapolu** [comment]
@enzief Why did you use  `Versions`?
Compiler says :
`warning: object Versions in package scalafix is deprecated (since 0.6.0): Use scalafix.sbt.BuildInfo instead lazy val V = _root_.scalafix.Versions`

**Comment by vovapolu** [comment]
I've resealed 0.1.2 version with your changes

**Comment by enzief** [comment]
@vovapolu The build doesn't compile with `scalafix.sbt.BuildInfo`, that's why I changed.
```
[success] Total time: 1 s, completed Mar 29, 2019 11:17:03 AM
/Users/enzief/work/round/scaluzzi/scalafix/build.sbt:30: error: value version is not a member of object scalafix.sbt.BuildInfo
  libraryDependencies += "ch.epfl.scala" %% "scalafix-core" % V.version,
                                                                ^
/Users/enzief/work/round/scaluzzi/scalafix/build.sbt:47: error: value version is not a member of object scalafix.sbt.BuildInfo
    libraryDependencies += "ch.epfl.scala" % "scalafix-testkit" % V.version % Test cross CrossVersion.full
```

And that's because scaluzzi only depends on `scalafix-core`, to get it to work with the other build info object we have to add the dependency `scalafix-interfaces`.

I can make a following PR for it if you feel necessary.

**Pull request merged**
