### PR TITLE
update Scala 2.12.10 and scalafix 0.9.7

### PR DESCRIPTION
**Pull request by enzief**
Couldn't find needed info in sclafix `BuildInfo` anymore so I track it manually.

### CODE REVIEW

**Comment by enzief** [comment]
@vovapolu would you please have a look? There is one test failing, any pointer is great!

**Comment by vovapolu** [comment]
@enzief I found https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/6. I saw such error before, you need just add `dist: trusty` to `.travis.yml`, ping me if this won't work.

**Comment by enzief** [comment]
This time really a test fails. I have it failing locally too. No idea how to fix, I've never looked into scalafix.

**Comment by vovapolu** [comment]
I think you just have to change here https://github.com/vovapolu/scaluzzi/blob/6f503d1768697b5135aec00ff351ac50320e4dbf/scalafix/input/src/main/scala/test/DisableSimple.scala#L67 from `any2stringadd[List[Int]](*)` to `Predef.any2stringadd[List[Int]](*)`, I suspect there were some changes in new scalafix version in symbol's name displaying.

**Comment by enzief** [comment]
It works perfectly. Thanks!

**Comment by vovapolu** [comment]
@enzief just published 0.1.3 version with new changes

**Pull request merged**
